# Generated by Django 2.1.15 on 2020-10-10 23:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('user_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
